### ISSUE TITLE
Chrome: Error 325 (net::ERR_RESPONSE_HEADERS_TOO_BIG): Unknown error.

### ISSUE THREAD

**Issue by PowerKiKi** [firephp/firephp-core#10]
It looks like Chrome (used with [FirePHP4Chrome](https://chrome.google.com/webstore/detail/firephp4chrome/gpgbmonepdpnacijbbdijfbecmgoojma)) has the lowest limit for headers size [according to StackOverflow](http://stackoverflow.com/questions/3326210/can-http-headers-be-too-big-for-browsers) of 256kb for all headers.

This can quickly be a problem when using `$firephp->trace()` where stacktrace dumps can get huge.

The obvious way to solve that, would be to detect the browser and truncate the size of headers, including a warning for developers at the end of logs.

But maybe it could be much cleaner to combine effort with https://github.com/aaronsaray/FirePHP4Chrome and @aaronsaray and introduce a new optional header sent from FirePHP4Chrome, which would trigger a limit on header size.

What would seem the best approach ?

Also see, similar issue (and how they solved it): https://github.com/Seldaek/monolog/issues/172

**Comment by PowerKiKi** [comment]
Closing due to lack of interest from core developers.

**Comment by cadorn** [comment]
I am going to be looking at this later this year. Will be doing an update to FirePHP on server and client.

**Comment by markusp72** [comment]
+1

**Comment by PowerKiKi** [comment]
@markusp72, I wouldn't hold my breath if I were you and move on to another project.

This project has not seen any significant activity in the last 2 years (if not more), and this specific issue was solved in #11, more than 3 years ago, but the maintainers never considered it good enough to be merged. Even though the original code base is really not up to modern standards.

**Comment by cadorn** [comment]
I am working on a new Web Extension here: https://github.com/firephp/firephp-for-firefox-devtools/issues/25

We can bring this functionality into the new extension and update FirePHPCore as things settle down.

I am charging ahead with FirePHP irrespective of other projects (like FirePHP4Chrome) now if that makes any difference.

@PowerKiKi I apologize for your frustrating experience (understandably so) contributing to FirePHP.

**Comment by aaronsaray** [comment]
Cool!  Just to clarify - I did implement the feature we discussed above in FirePHP4Chrome - even though it was just a suggestion.  If that particular implementation changes, I'm open to removing the code and applying a different solution.  Just been waiting... glad to hear there's some movement here now :)

**Comment by cadorn** [comment]
Will be solved by: https://github.com/firephp/firephp-core/issues/57
