### ISSUE TITLE
Zend\Log\Writer\FirePHP Can't output DEBUG info into firebug console

### ISSUE THREAD

**Issue by snowwolf007cn** [firephp/firephp-core#13]
FirePHP Version: 0.7.2
ZF Version:2.2.0

Try: $logger->debug(**METHOD**.$e->getMessage());
get error in console:
"There was a problem writing your data from the Wildfire Plugin http://meta.firephp.org/Wildfire/Structure/FirePHP/FirebugConsole/0.1"

SyntaxError: JSON.parse: unexpected character
Filtered chrome url chrome://firephp/content/lib/renderer.js

**Comment by cadorn** [comment]
Closing due to age. Please refine with latest releases if still applicable.
