### ISSUE TITLE
Exception : 'You must specify a label for the group!' (0 and "0")

### ISSUE THREAD

**Issue by bkdotcom** [firephp/firephp-core#18]
I just had a script crash and burn on this:

``` php
$firephp->group(0);
```

Exception : 'You must specify a label for the group!'

My suspicions were correct..    the group method is doing an "empty" test:

``` php
if (!$Name) {
    throw $this->newException('You must specify a label for the group!');
}
```

should be 
    if ( is_null($Name) )
or
    if ( !isset($Name) )

don't be hatin' 0 and "0" !  :)

**Comment by cadorn** [comment]
Can anyone tell me if this was solved by the PRs? /cc @bkdotcom
