### ISSUE TITLE
composer package abandoned?

### ISSUE THREAD

**Issue by glensc** [firephp/firephp-core#25]
https://packagist.org/packages/firephp/firephp-core

is marked abandoned and pointing to this repo, but seems pretty much active here. perhaps you marked abandoned by mistake? there's way to undo abandoned state in packagist.org

or what packagist repo should be used if that one is abandoned?

**Comment by zachborboa** [comment]
@Seldaek Would you be so kind as to transfer ownership of "php-curl-class/php-curl-class" to @php-curl-class. Thank you!

**Comment by Seldaek** [comment]
@zachborboa if you give me an actual packagist username then I can grant access to it and then you can configure the hook.

**Comment by Seldaek** [comment]
@zachborboa ah I saw you have a packagist account so I added you as maintainer, if you want another account you can add it yourself then :)

**Comment by zachborboa** [comment]
@Seldaek - many thanks!

**Comment by glensc** [comment]
@zachborboa don't hijack issues to contact Seldaek! this issue is regarding firephp-core, i do not see php-curl-class being relevant here.
