### ISSUE TITLE
License file in FirePHPCore library

### ISSUE THREAD

**Issue by ganiuszka** [firephp/firephp-core#32]
Hello,

I would add FirePHPCore library to Fedora Linux distribution as binary package. I noticed that in FirePHPCore there is not separate file with license text (usually LICENSE or LICENSE.txt). I have seen that license information is added to README file. Could I ask you about add MIT License text to dedicated for this file in repository?

Thank you in advance.

Best regards.
Marcin Haba

**Comment by cadorn** [comment]
Added: https://github.com/firephp/firephp-core/blob/master/LICENSE.txt

Thanks.

**Comment by ganiuszka** [comment]
Thank you for the LICENSE file. I appreciate it.
I believe that this change will make packaging process easier for potential packages maintainers in future either.

Best regards.
Marcin Haba
