### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by aicm** [firephp/firephp-core#33]
Hello,

This is my third time in the last year trying to make firephp work and now the website is down (documentation, as well as official). Firephp doesn't get any output from the server library either.

Therefore, it begs the question: is this project dead?

**Comment by cadorn** [comment]
Its not abandoned. I have just been swamped with other work.

I hope to reboot things soon.

You need to make sure the net and console panels are enabled. There are lots of tutorials and other info on google.

I apologize for the poor experience using FirePHP right now. I hope to turn that around later this year.
