### ISSUE TITLE
firephp.org down

### ISSUE THREAD

**Issue by AhmedHasnaoui** [firephp/firephp-core#34]
The webseite http://firephp.org is down.
I installed firephp 0.7.4.1-signed  with firebug 2.0.12 and FF 41.0
FirePHP is not showing up...

The requirements in the FF addons store says:

"Requirements (Firefox 8+):

```
You must have Firebug 1.9+ installed and the Firebug "Console" and "Net" panels enabled to use this extension.
You must also download a PHP library from http://www.firephp.org/ and include it in your application."
```

I can't get that PHP library because firephp.org is not accessible.

**Comment by sssmith** [comment]
Firephp.org is still down. I also am trying to install Firephp.   Does anyone know an alternative source of the backend code and instructions for installation?  The Firefox browser extension is still available from Firebug but appears useless without the backend code.

**Comment by cadorn** [comment]
The backend library is here: https://github.com/firephp/firephp-core (this repository)

The extension is here: https://addons.mozilla.org/en-us/firefox/addon/firephp/

There are lots of tutorials online that go through how to install it.

I will be updating the FirePHP site and testing everything in the next couple of weeks.

**Comment by sssmith** [comment]
Thanks!  I have successfully ‘echoed’ a php variable to the Firebug console so I think I will be good with this.  I will try the new version when it is available as well.  

 

Steve Smith

585.764.9611

**Comment by jiaojie1989** [comment]
We are glad to see you are doing a lot work.
But the firephp.org site is still down now.

**Comment by cadorn** [comment]
Its coming. Not much longer now.

**Comment by shayneo-harmonic** [comment]
Don't be afraid to ask for help from the community if your snowed under buddy. :)

**Comment by si458** [comment]
still offline at moment, do you need help? im sure the community would love to help!

**Comment by IWriteThings** [comment]
The site is still down. It may be helpful to get some kind of placeholder site up, even if it is just an index.html with some links to the github repository. I could make you one this weekend if you would like.

**Comment by cadorn** [comment]
> It may be helpful to get some kind of placeholder site up

That's a good idea. I have specific things I want to do on the new site; just have not had the chance to get working on it yet.

I'll setup something that renders markdown on the domain. I can then dump all the existing integration info and links into pages that need to be reviewed for accuracy.

I would welcome any and all help to fine-tune the content once its up.

I think I mentioned it elsewhere. I have a new implementation of the client I hope to release in the coming months to reboot the project.

**Comment by IWriteThings** [comment]
@cadorn Awesome! Sounds like a good idea. Can you toss a link in here to the repository for people finding this by way of 'the google' when you do it? I assume you will just be using github pages and let the URL redirect to that?

https://pages.github.com/

There is a ton of integration that can be done between pages and your repos. So every time you do an update or post some new code - it will reflect on the page and people can be kept up to date. My only other recommendation is to integrate that into an RSS feed available off of the pages site. I personally wouldn't mind adding you to my newsbeuter list. =)

Thanks for all the hard work!

**Comment by marsjaninzmarsa** [comment]
Umm... Bump? It's still down...

**Comment by cadorn** [comment]
Oh so close. I finally decided on how to built the site going forward after trying a couple of approaches.

**Comment by tchalvak** [comment]
Yeah, if github pages were used, it'd be pretty easily mirrorable, so that even if you created a static site at firephp.org, the pages could change and be accessible via github pages pretty consistently.

**Comment by cadorn** [comment]
The start of the new site is up now: http://firephp.org/

The source code is at: https://github.com/firephp/firephp.org

I apologize for having the site down for so long and the lack of attention to FirePHP. I got somewhat lost building the next major iteration of FirePHP but its time now to tie it all back in using all the latest web stack to where it all started for me: FirePHP

I am planning on keeping the content on the firephp.org site minimal and to the point and start highlighting all the extensions the community has written along with live examples that are installable and runnable on the firephp.org docker instance.

Most of the existing content is old and the links are broken. I think it will make much more sense to survey what is out there now and highlight what is worthwhile.

I welcome any PRs to complete the minimal docs for FirePHP.

I am somewhat out of touch with what has been happening in the PHP community (having had an intense focus on JavaScript) and am looking for suggestions as to which FirePHP integrations are popular. I want to write a few sample FirePHP Integration Demos that will run on the docker image and then showcase them on firephp.org so others can add their own.

**Comment by si458** [comment]
very basic, very simple, but wonderful...
its all you need at the moment to point people in the correct direction :)

**Comment by tchalvak** [comment]
Thanks for the work @cadorn , it's good to know that the extension is still going (php needs more useful dev tools like this).

**Comment by cadorn** [comment]
I have started work on a new Web Extension and it is starting to work: https://github.com/firephp/firephp-for-firefox-devtools

Once it is reliable enough I will update all the docs and website.

Thanks for all the patience. Looking forward to hearing what you think!
