### ISSUE TITLE
The link to your documentation is not working

### ISSUE THREAD

**Issue by eldan88** [firephp/firephp-core#36]
http://docs.sourcemint.org/firephp.org/firephp/1/-docs/

**Comment by gitbnw** [comment]
https://github.com/firephp/firephp/blob/master/docs/Configuration/Traditional.md

**Comment by cadorn** [comment]
I am rebooting FirePHP starting with a new Web Extension here: https://github.com/firephp/firephp-for-firefox-devtools

Once that works reliably enough I will get to reviewing the server libraries and docs.

**Comment by cadorn** [comment]
See: https://github.com/firephp/firephp-core/issues/43
