### ISSUE TITLE
fb() func isn't working

### ISSUE THREAD

**Issue by Sogl** [firephp/firephp-core#37]
Hi!

I'm trying to use firephp with composer. I added this library to my project, my `composer.json`:

```
{
    "name": "mezin.a/hashids",
    "require": {
        "hashids/hashids": "^1.0",
        "firephp/firephp-core": "^0.4.0"
    }
}
```

Next step is `index.php`:

``` php
<?php
    error_reporting(E_ALL ^ E_DEPRECATED);
    ini_set("display_errors", 1);

    require 'vendor/autoload.php';

    fb('111');
?>
```

Got an error:

```
Fatal error: Call to undefined function fb()
```

Works only with these lines:

``` php
$firephp = FirePHP::getInstance(true);
$firephp->fb('value', 'var', FirePHP::WARN);
```

How to get it working with `fb()` only?

**Comment by Sogl** [comment]
Works also with `fb::send('test')`, but I want to shorter line.

**Comment by twcooper3** [comment]
You should include fb.php:

`require_once('/var/www/html/FirePHPCore/fb.php');`

**Comment by cadorn** [comment]
Seems like the autoloading does not expose the global `fb()` function. We can fix that as part of the composer related updates: https://github.com/firephp/firephp-core/issues/44

**Comment by cadorn** [comment]
Confirmed that function is available via a test: https://github.com/firephp/firephp-core/blob/eea75c30310fea699c6a78955445270475e266c9/tests/Features/12-FB.php#L13
