### ISSUE TITLE
Since firebug has been embedded into Firefox, FirePHP is no longer working.

### ISSUE THREAD

**Issue by vpominchuk** [firephp/firephp-core#39]
Since firebug has been embedded into Firefox, FirePHP is no longer working.

Firefox: 51.0.1
Firebug: embedded
Firephp: 0.7.4.1

**Comment by vordan** [comment]
You have toi enable Server Log in the console panel to see the messages.
It works, but shows the labels at the end

**Comment by Nrde** [comment]
Firebug 2.0.19 doesn't show the console logs with FF 49 anymore either. Firebug doesn't have a server log anywhere? Can you point exactly where it is?

**Comment by brasofilo** [comment]
I installed [Firebug](https://addons.mozilla.org/en-US/firefox/addon/firebug/reviews/?src=api) and it's working for me now

**Comment by cadorn** [comment]
There is a new Web Extension for FirePHP here: https://github.com/firephp/firephp-for-firefox-devtools
