### ISSUE TITLE
@param mixes - mistype?

### ISSUE THREAD

**Issue by Hissvard** [firephp/firephp-core#49]
There's something that's been bothering my IDE for a while.

https://github.com/firephp/firephp-core/blob/ea6a06a0429022da64c5fcc6a0ac35d344159573/lib/FirePHPCore/FirePHP.class.php#L572

Is this a mistype of `@param mixed`, by any chance? It's only in a couple places so I can submit a quick PR if needed.

**Comment by cadorn** [comment]
Yeah, that is a spelling mistake. Feel free to submit a PR.

**Comment by cadorn** [comment]
Done: https://github.com/firephp/firephp-core/pull/50
