### ISSUE TITLE
Option for call location trace displacement

### ISSUE THREAD

**Issue by tylla** [firephp/firephp-core#51]
I am trying to introduce FirePHP to an existing project. (BTW I really love the whole concept)
The project uses a 'home made' but quite nice log system which offers a simple opportunity to use FirePHP-Core from one central location, but this poses a problem. All the log entries in the devtools FirePHP log show exact the same calling location, no wonder as this is the single place where FB::log() gets called.
This could be solved easily if FirePHP had an option to ignore the first 'n' entries from the trace but I couldn't find such an option (I tried to take a look into the code but no result).
Does such option exist (and I overlooked it) or if not could it be added?

**Comment by cadorn** [comment]
I should get to this soon. The FirePHPCore lib is going to get some tests and then some improvements.

**Comment by cadorn** [comment]
`lineNumberOffset` option now on master: https://github.com/firephp/firephp-core/blob/master/tests/Features/09-Wrappers.php#L51

**Comment by tylla** [comment]
Nice job. Works as it should.
Thanks!
