### ISSUE TITLE
New release - php 7.4

### ISSUE THREAD

**Issue by ctrlaltca** [firephp/firephp-core#63]
Can you please tag a new release that includes commit3f5dd60206c5a8814d9de3320ed3e9f0469938c7 ?
Now that php 7.4 is officially out, it's needed to avoid error messages.

**Comment by cadorn** [comment]
Done.

**Comment by cadorn** [comment]
Thanks for the reminder.

**Comment by ctrlaltca** [comment]
Thank you!
