### ISSUE TITLE
phar: stub.php

### ISSUE THREAD

**Issue by bingalls** [firephp/firephp-core#8]
firephp 1.0.0b1rc8 logs warnings:
PHP Warning:  include(phar:///usr/.../firephp-1.0.0b1rc8.lib.phar/stub.php): failed to open stream: phar error: "stub.php" is not a file in phar "/usr/.../firephp-1.0.0b1rc8.lib.phar" in /usr/.../firephp-1.0.0b1rc8.lib.phar on line 9

**Comment by cadorn** [comment]
The **pear** release channel is no longer supported. You can get FirePHP via composer and there will be new official releases via composer as well. See: https://github.com/firephp/firephp-core/issues/44

There will also be `phar` packages releases available via the composer package or on github.
